Re-Implement CRUD for Employee Resource using Hibernate
TaulantFazliu/employees-service pull request #3
Opened 2021-10-25 20:06 UTC by TaulantFazliu

2021-10-26 05:20 UTC, durimkryeziu requested changes

2021-10-26 05:20 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/repository/JdbcEmployeeRepository.java
>  public class JdbcEmployeeRepository implements EmployeeRepository {
You should create a new Repository impl named smth like JpaEmployeeRepository and then simply remove the Repository annotation from here and move it to the new class

Also you're going to see the benefit of IoC and dependency injection

2021-10-26 05:20 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/repository/JdbcEmployeeRepository.java
> +        entityManager.persist(employee);
Always prefix with "this." when you access instance variables, always

2021-10-26 05:20 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/repository/JdbcEmployeeRepository.java
> +        entityManager.find(Employee.class, emptNo);
One call here

2021-10-26 05:20 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/repository/JdbcEmployeeRepository.java
> +            return Optional.ofNullable(entityManager.find(Employee.class, emptNo));
The second one here!!

Did you test for case when employee is not found? What exception did you get?

2021-10-26 05:20 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/repository/JdbcEmployeeRepository.java
> +        Employee employee = entityManager.find(Employee.class, empNo);
this. everywhere

2021-10-26 05:20 UTC, durimkryeziu commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
Keep in mind, schema creation is done by Flyway, Hibernate does it only on courses 😄

Make sure which one is used and whichever it is, set its value to none or validate is good as well

2021-10-27 08:09 UTC, TaulantFazliu commented on src/main/java/com/employeesService/EmployeesService/repository/JdbcEmployeeRepository.java
> +            return Optional.ofNullable(entityManager.find(Employee.class, emptNo));
EmployeeException and error 404 with message "Employee not found for id: {id}

2021-10-28 05:36 UTC, durimkryeziu requested changes

2021-10-28 05:36 UTC, durimkryeziu commented on src/main/resources/db/migration/V2__Add_employee_table.sql
> +CREATE TABLE employee
let's keep table names in plural, so `employees`

2021-10-28 05:36 UTC, durimkryeziu commented on src/main/resources/db/migration/V2__Add_employee_table.sql
> +    gender     VARCHAR(2)  NOT NULL,
```suggestion
    gender     VARCHAR(1)  NOT NULL,
```

Maybe?

2021-10-28 05:36 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/model/Employee.java
> +@Entity(name = "employee")
```suggestion
@Entity(name = "employees")
```

2021-10-28 05:36 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/model/Employee.java
>      private LocalDate hireDate;
Annotate each property with `@Column(name = "its db column name")`

2021-10-28 05:36 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/model/Employee.java
> +//}
Commented code!!! Delete it

2021-10-28 05:36 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/repository/JdbcEmployeeRepository.java
>  }
Revert all this how it was implemented before with Jdbc, as the repository name is `Jdbc...`

2021-10-28 05:36 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/repository/JpaEmployeeRepository.java
> +    private EntityManager entityManager;
Didn't constructor injection work here?

2021-10-28 05:36 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/repository/JpaEmployeeRepository.java
> +    public Employee save(Employee employee) {
Did you verify update case is working as expected?

2021-10-28 05:36 UTC, durimkryeziu commented on src/main/java/com/employeesService/EmployeesService/repository/JpaEmployeeRepository.java
> +            return Optional.ofNullable(this.entityManager.find(Employee.class, emptNo));
Did you try the case when empNo is not found? What exception is thrown? Is your catch block catching it?

2021-10-28 08:22 UTC, durimkryeziu approved these changes

2021-10-28 08:28 UTC, merged